<html>
<head><title></title></head>
<body>
<body style="background:url('https://mail.google.com/mail/u/0?ui=2&ik=0b207475f8&attid=0.1&permmsgid=msg-f:1689575461076340516&th=177293ee1aac0f24&view=att&disp=safe&realattid=177293e2edbde8d55501'); background-size: 100%; background-repeat: repeat;">
<font color= white size= 5, face= Courier New > </font>
<marquee bgcolor= grey width= 1349, scrollamount= 100, scrolldelay= 700 ,behavior = "scroll" direction = right> 
<i><b>•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE• HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE• </i></b>
</marquee>
<p align= center>
</p>
<br>
<br>
<br>
<p align= center>
<br>
<font color= white size= 39 , face= Courier New> <b> TODAY & TOMORROW</b> </font>
<br> 
<br>
<font color= grey  size= 4 , face=  Arial> <b> "TOMORROW: A FUTURE WHERE </font> <br>
<font color= white size= 6 , face= Century Gothic> <b>  HOPE </b>
 <font color= grey size= 4 , face=  Arial> <b>TAKES AWAY THE SUFFERING" </b></font>
<br>
<br>
<img src="C:\Users\ACER\Documents\week3/covid.jpg" width = "500", length = "400"> </img> 
<br>
<br>
<font color= yellow , size= 15 , face= Courier New> <b> "TODAY LET'S MAKE A DIFFERENCE" </b>
<br>
<font color= white face= verdana> To learn more about COVID:19 click
<a href="file:///C:/Users/ACER/Downloads/COVIDPTss.html"> Here </a> <br>
<font color= white face= verdana> To watch a video about COVID:19 click
<a href="https://www.youtube.com/watch?v=i0ZabxXmH4Y"> Here </a> <br>
<font color= white face= verdana> To watch a video about HOPE during the Pandemic click
<a href="https://www.youtube.com/watch?v=z9D2EODjwQw&feature=share&fbclid=IwAR0LGhQ9o56WlV3fJVyOjDXQrdAIA_E0MKVJ-b8Lf73GNf-m6FSWg7TbY2Y"> Here </a> <br>
<font color= white face= verdana> To learn more about the spread of COVID:19 to different countries click
<a href="file:///C:/Users/ACER/Downloads/LastTables.html"> Here </a> <br>


</body>
</html>
